import { Type } from 'class-transformer';
import { IsOptional, IsString, IsBoolean, IsArray, ValidateNested } from 'class-validator';
import { DomainResource } from '../base/domain-resource.js';
import { CodeableConcept } from '../datatypes/codeable-concept.js';
import { Identifier } from '../datatypes/identifier.js';
import { Period } from '../datatypes/period.js';
import { Reference } from '../datatypes/reference.js';

/** FHIR R4 Schedule — a container for slots of time that may be available for booking appointments. */
export class Schedule extends DomainResource {

  readonly resourceType = 'Schedule';

  /** External identifiers for this schedule. */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => Identifier)
  identifier?: Identifier[];

  /** Whether this schedule record is in active use. */
  @IsOptional()
  @IsBoolean()
  active?: boolean;

  /** A broad categorization of the service that is to be performed during this appointment. */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CodeableConcept)
  serviceCategory?: CodeableConcept[];

  /** The specific service that is to be performed during this appointment. */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CodeableConcept)
  serviceType?: CodeableConcept[];

  /** The specialty of a practitioner that would be required to perform the service requested. */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CodeableConcept)
  specialty?: CodeableConcept[];

  /** Slots that reference this schedule resource provide the availability details to these referenced resource(s). */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => Reference)
  actor?: Reference[];

  /** The period of time that the slots generated by this schedule cover. */
  @IsOptional()
  @ValidateNested()
  @Type(() => Period)
  planningHorizon?: Period;

  /** Comments on the availability to describe any extended information. */
  @IsOptional()
  @IsString()
  comment?: string;

  /** Creates a new Schedule. @param props - Initial values. */
  constructor(props?: Partial<Schedule>) {
    super();

    if (props) {
      Object.assign(this, props);
    }
  }

  /** Adds an item to the identifier array. @returns This instance for chaining. */
  addIdentifier(item: Identifier): this {
    if (!this.identifier) {
      this.identifier = [];
    }

    this.identifier.push(item);

    return this;
  }

  /** Adds an item to the serviceCategory array. @returns This instance for chaining. */
  addServiceCategory(item: CodeableConcept): this {
    if (!this.serviceCategory) {
      this.serviceCategory = [];
    }

    this.serviceCategory.push(item);

    return this;
  }

  /** Adds an item to the serviceType array. @returns This instance for chaining. */
  addServiceType(item: CodeableConcept): this {
    if (!this.serviceType) {
      this.serviceType = [];
    }

    this.serviceType.push(item);

    return this;
  }

  /** Adds an item to the specialty array. @returns This instance for chaining. */
  addSpecialty(item: CodeableConcept): this {
    if (!this.specialty) {
      this.specialty = [];
    }

    this.specialty.push(item);

    return this;
  }

  /** Adds an item to the actor array. @returns This instance for chaining. */
  addActor(item: Reference): this {
    if (!this.actor) {
      this.actor = [];
    }

    this.actor.push(item);

    return this;
  }
}
