export enum QuestionnaireItemType {
  Group = 'group',
  Display = 'display',
  Boolean = 'boolean',
  Decimal = 'decimal',
  Integer = 'integer',
  Date = 'date',
  DateTime = 'dateTime',
  Time = 'time',
  String = 'string',
  Text = 'text',
  Url = 'url',
  Choice = 'choice',
  OpenChoice = 'open-choice',
  Attachment = 'attachment',
  Reference = 'reference',
  Quantity = 'quantity',
}
